project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "blogs/Final Presentation/final_presentation.qmd"
    - "!blogs/HW1/hw1_questions.qmd"
    - "!blogs/HW2/hw2_questions.qmd"
    - "!blogs/HW3/hw3_questions.qmd"
    - "!blogs/HW4/hw4_questions.qmd"

website:
  title: "Eesha Jagdhane"
  navbar: false

format:
  html:
    theme: none
    toc: false
